[package]
name = "connex-tui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.rand]
version = "0.8.5"

[dependencies.tui]
version = "0.18"
default-features = false
features = ["crossterm"]

[dependencies.crossterm]
version = "0.23"

[dependencies.connex]
version = "0.1.0"
path = "../connex"
features = ["random"]
